name: Glasgow Signs
favicon: null
layout_spectrum: 0.09824102697893977
typography_spectrum: 0.1278263540007174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7348135528154671
  lightness: 0.07707303296774626
  saturation: 0.5441633346490562
  rhythmicContrast: 0.43771635950542986
purpose: []
