name: Glasgow Signs
favicon: null
layout_spectrum: 0.09824102697893977
typography_spectrum: 0.1278263540007174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030102'
    - '#72757c'
    - '#41b5a8'
    - '#dad9de'
    - '#d13539'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
