name: Glasgow Signs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#abadac'
    - '#000000'
    - '#2e4042'
    - '#637977'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
