name: Glasgow Signs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030102'
    - '#72757c'
    - '#41b5a8'
    - '#dad9de'
    - '#d13539'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
